version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./internal/redis/data:/data

  app1:
    build:
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - 8080:8080
    depends_on:
      - redis

  app2:
    build:
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - 8081:8080
    depends_on:
      - redis